version: '3.8'

services:
  frontend-dev:
    container_name: nextjs_web_dev
    image: nextjs-web-dev:1.0.0
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    command: npm start
    ports:
      - 3000:3000
    networks:
      - nestjs-network
    depends_on:
      - backend-dev
    volumes:
      - ./frontend:/usr/src/web-app
      - /usr/src/web-app/node_modules
  backend-dev:
    container_name: nestjs_api_dev
    image: nestjs-api-dev:1.0.0
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: npm start
    ports:
      - 8080:3000
    environment:
      - MONGO_URL=mongodb://mongodb:27017/simple-trace-together
      - SERVER_PORT=3000
    networks:
      - nestjs-network
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - ./databases:/data/db
    ports:
      - 27017:27017
    networks:
      - nestjs-network
    restart: always

networks:
  nestjs-network:
    driver: bridge
